[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
rowan.workspace = true
char-classes.workspace = true
expect-test.workspace = true
text-size.workspace = true
dissimilar.workspace = true
either.workspace = true
